language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle